import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from '@next/font/local'
import BottomNav from "./ui/bottomnav";
import MobileToolbar from "./ui/mobiletoolbar";
import "./globals.css";
import Toolbar from "./ui/toolbar";



const inter = Inter({ subsets: ["latin"] });


const irans = localFont({
  src: '../public/font/irans.ttf'


})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="">
  
        <Toolbar/>
        <div className="">
        {children}
        </div>
        <BottomNav />
      </body>
    </html>
  );
}
